name: Build SO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Build Tools
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Configure and Build
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-so
        path: build/*.so
